#!/usr/bin/env python

import optparse
import os
import sys
import inspect
models_dir = os.path.realpath(os.path.abspath(os.path.join(os.path.split(inspect.getfile( inspect.currentframe() ))[0],"models")))
if models_dir not in sys.path:
     sys.path.insert(0, models_dir)
import ibm1_f2e
import ibm1_e2f

optparser = optparse.OptionParser()
optparser.add_option("-d", "--data", dest="train", default="en600.468/aligner/data/hansards", help="Data filename prefix (default=data)")
optparser.add_option("-n", "--num_sentences", dest="num_sents", default=sys.maxint, type="int", help="Number of sentences to use for training and alignment")
optparser.add_option("-m", "--model", dest="smt_model", default="f2e", help="SMT word alignment model")
(opts, _) = optparser.parse_args()

if opts.smt_model == "f2e":
    ibm1_f2e.IBM1(opts.train, opts.num_sents)
elif opts.smt_model == "e2f":
    ibm1_e2f.IBM1(opts.train, opts.num_sents)
